name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  RabbitMQ_HelloWorld:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: ${GITHUB_WORKSPACE}/Communication_Library/MaessageBroker/build_all.sh
      -
        name: Test
        run: ${GITHUB_WORKSPACE}/Communication_Library/MaessageBroker/run_all.sh
          
