name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  RabbitMQ_HelloWorld:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: |
          cd ./Communication_Library/MessageBroker
          chmod +x ./build_all.sh
          ./build_all.sh
      -
        name: Test
        run: |
          cd ./Communication_Library/MessageBroker
          chmod +x ./run_all.sh.sh
          ./run_all.sh.sh
          
